---

<% if ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
driver:
  name: digitalocean
  size: 512mb

platforms:
- name: centos-7-0-x64
  transport:
    ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
    max_wait_until_ready: 30
- name: ubuntu-14-04-x64
  transport:
    ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
    max_wait_until_ready: 30
- name: ubuntu-16-04-x64
  transport:
    ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
    max_wait_until_ready: 30
- name: debian-8-x64
  # DO debian image doesn't have sudo
  provisioner:
    sudo: false
  verifier:
    sudo: false
  transport:
    ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
    max_wait_until_ready: 30
<% else %>
driver:
  name: vagrant

platforms:
- name: bento/centos-7.2
- name: bento/ubuntu-14.04
- name: bento/ubuntu-16.04
- name: bento/debian-8.4
<% end %>

provisioner:
  name: chef_zero
  attributes:
    rkt:
      install:
        kernel_check: false

verifier:
  name: inspec
  # https://github.com/chef/inspec/issues/820
  # https://github.com/chef/kitchen-inspec/issues/92
  format: progress
  inspec_tests:
    - test/integration-shared/default

suites:
  - name: default
    run_list:
      - recipe[rkt::default]
      - recipe[rkt_test::default]
  - name: without-sudo
    run_list:
      - recipe[rkt::default]
      - recipe[rkt_test::default]
    attributes:
      rkt:
        install:
          tgz:
            sudo: false
  - name: packages
    run_list:
      - recipe[rkt::default]
      - recipe[rkt_test::default]
    attributes:
      rkt:
        install:
          type: 'package'
    verifier:
      inspec_tests:
        - test/integration-shared/default
        - test/integration-shared/packages
  - name: testing-packages
    run_list:
      - recipe[rkt::default]
      - recipe[rkt_test::default]
    attributes:
      rkt:
        install:
          type: 'package'
          package:
            repository_base_location: http://download.opensuse.org/repositories/home:/artem_sidorenko:/rkt:/testing
    verifier:
      inspec_tests:
        - test/integration-shared/default
        - test/integration-shared/packages
