---

<% if ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
driver:
  name: digitalocean
  size: 512mb

platforms:
- name: centos-7-0-x64
  transport:
   ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
- name: ubuntu-14-04-x64
  transport:
   ssh_key: "<%= ENV['CI_SSH_KEY'] %>"
<% else %>
driver:
  name: vagrant

platforms:
- name: bento/centos-7.2
- name: bento/ubuntu-14.04
<% end %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[rkt::default]
  - name: without-sudo
    run_list:
      - recipe[rkt::default]
    attributes:
      rkt:
        install:
          tgz:
            sudo: false
